### ISSUE TITLE
Espacio de Noticias 2pts.

### ISSUE THREAD

**Issue by Marin216** [PrograMovil-158-24/Grupo5_Lab_1#2]
Crear	un	widgets	que	permita	mostrar	mediante	cards	
con	un	body	que	contenga	imágenes	y	texto	de	noticias	importantes	de	la	universidad.

**Comment by AlejandroCas26** [comment]
https://github.com/PrograMovil-158-24/Grupo5_Lab_1/tree/2-espacio-de-noticias-2pts
